//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePrototypeApplication.SOAPServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPServiceReference.SOAPWebServiceSoap")]
    public interface SOAPWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EmployeePrototypeApplication.SOAPServiceReference.HelloWorldResponse HelloWorld(EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.HelloWorldResponse> HelloWorldAsync(EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginValidation", ReplyAction="*")]
        EmployeePrototypeApplication.SOAPServiceReference.LoginValidationResponse LoginValidation(EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginValidation", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.LoginValidationResponse> LoginValidationAsync(EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequest request);
        
        // CODEGEN: Generating message contract since element name EmployeeNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeName", ReplyAction="*")]
        EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameResponse EmployeeName(EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeName", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameResponse> EmployeeNameAsync(EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequest request);
        
        // CODEGEN: Generating message contract since element name EmployeeAddressResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeAddress", ReplyAction="*")]
        EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressResponse EmployeeAddress(EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressResponse> EmployeeAddressAsync(EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequest request);
        
        // CODEGEN: Generating message contract since element name EmployeePhoneNumberResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeePhoneNumber", ReplyAction="*")]
        EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberResponse EmployeePhoneNumber(EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeePhoneNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberResponse> EmployeePhoneNumberAsync(EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequest request);
        
        // CODEGEN: Generating message contract since element name userid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadData", ReplyAction="*")]
        EmployeePrototypeApplication.SOAPServiceReference.LoadDataResponse LoadData(EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadData", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.LoadDataResponse> LoadDataAsync(EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequest request);
        
        // CODEGEN: Generating message contract since element name userid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitRequest", ReplyAction="*")]
        EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestResponse SubmitRequest(EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestResponse> SubmitRequestAsync(EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalendarCompareDateValidation", ReplyAction="*")]
        bool CalendarCompareDateValidation(System.DateTime StartDate, System.DateTime EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalendarCompareDateValidation", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CalendarCompareDateValidationAsync(System.DateTime StartDate, System.DateTime EndDate);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EmployeePrototypeApplication.SOAPServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginValidationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginValidation", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequestBody Body;
        
        public LoginValidationRequest() {
        }
        
        public LoginValidationRequest(EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginValidationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginValidationRequestBody() {
        }
        
        public LoginValidationRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginValidationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginValidationResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.LoginValidationResponseBody Body;
        
        public LoginValidationResponse() {
        }
        
        public LoginValidationResponse(EmployeePrototypeApplication.SOAPServiceReference.LoginValidationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginValidationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginValidationResult;
        
        public LoginValidationResponseBody() {
        }
        
        public LoginValidationResponseBody(int LoginValidationResult) {
            this.LoginValidationResult = LoginValidationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeName", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequestBody Body;
        
        public EmployeeNameRequest() {
        }
        
        public EmployeeNameRequest(EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmployeeNameRequestBody {
        
        public EmployeeNameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameResponseBody Body;
        
        public EmployeeNameResponse() {
        }
        
        public EmployeeNameResponse(EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmployeeNameResult;
        
        public EmployeeNameResponseBody() {
        }
        
        public EmployeeNameResponseBody(string EmployeeNameResult) {
            this.EmployeeNameResult = EmployeeNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeAddress", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequestBody Body;
        
        public EmployeeAddressRequest() {
        }
        
        public EmployeeAddressRequest(EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmployeeAddressRequestBody {
        
        public EmployeeAddressRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeeAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeeAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressResponseBody Body;
        
        public EmployeeAddressResponse() {
        }
        
        public EmployeeAddressResponse(EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeeAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmployeeAddressResult;
        
        public EmployeeAddressResponseBody() {
        }
        
        public EmployeeAddressResponseBody(string EmployeeAddressResult) {
            this.EmployeeAddressResult = EmployeeAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeePhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeePhoneNumber", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequestBody Body;
        
        public EmployeePhoneNumberRequest() {
        }
        
        public EmployeePhoneNumberRequest(EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmployeePhoneNumberRequestBody {
        
        public EmployeePhoneNumberRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmployeePhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmployeePhoneNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberResponseBody Body;
        
        public EmployeePhoneNumberResponse() {
        }
        
        public EmployeePhoneNumberResponse(EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmployeePhoneNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmployeePhoneNumberResult;
        
        public EmployeePhoneNumberResponseBody() {
        }
        
        public EmployeePhoneNumberResponseBody(string EmployeePhoneNumberResult) {
            this.EmployeePhoneNumberResult = EmployeePhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadData", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequestBody Body;
        
        public LoadDataRequest() {
        }
        
        public LoadDataRequest(EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        public LoadDataRequestBody() {
        }
        
        public LoadDataRequestBody(string userid) {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.LoadDataResponseBody Body;
        
        public LoadDataResponse() {
        }
        
        public LoadDataResponse(EmployeePrototypeApplication.SOAPServiceReference.LoadDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.ArrayOfString LoadDataResult;
        
        public LoadDataResponseBody() {
        }
        
        public LoadDataResponseBody(EmployeePrototypeApplication.SOAPServiceReference.ArrayOfString LoadDataResult) {
            this.LoadDataResult = LoadDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitRequest", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequestBody Body;
        
        public SubmitRequestRequest() {
        }
        
        public SubmitRequestRequest(EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime EndDate;
        
        public SubmitRequestRequestBody() {
        }
        
        public SubmitRequestRequestBody(string userid, System.DateTime StartDate, System.DateTime EndDate) {
            this.userid = userid;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestResponseBody Body;
        
        public SubmitRequestResponse() {
        }
        
        public SubmitRequestResponse(EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SubmitRequestResponseBody {
        
        public SubmitRequestResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SOAPWebServiceSoapChannel : EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPWebServiceSoapClient : System.ServiceModel.ClientBase<EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap>, EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap {
        
        public SOAPWebServiceSoapClient() {
        }
        
        public SOAPWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAPWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeePrototypeApplication.SOAPServiceReference.HelloWorldResponse EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.HelloWorld(EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequestBody();
            EmployeePrototypeApplication.SOAPServiceReference.HelloWorldResponse retVal = ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.HelloWorldResponse> EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.HelloWorldAsync(EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.HelloWorldResponse> HelloWorldAsync() {
            EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.HelloWorldRequestBody();
            return ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeePrototypeApplication.SOAPServiceReference.LoginValidationResponse EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.LoginValidation(EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequest request) {
            return base.Channel.LoginValidation(request);
        }
        
        public int LoginValidation(string username, string password) {
            EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            EmployeePrototypeApplication.SOAPServiceReference.LoginValidationResponse retVal = ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).LoginValidation(inValue);
            return retVal.Body.LoginValidationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.LoginValidationResponse> EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.LoginValidationAsync(EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequest request) {
            return base.Channel.LoginValidationAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.LoginValidationResponse> LoginValidationAsync(string username, string password) {
            EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.LoginValidationRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).LoginValidationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameResponse EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.EmployeeName(EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequest request) {
            return base.Channel.EmployeeName(request);
        }
        
        public string EmployeeName() {
            EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequestBody();
            EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameResponse retVal = ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).EmployeeName(inValue);
            return retVal.Body.EmployeeNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameResponse> EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.EmployeeNameAsync(EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequest request) {
            return base.Channel.EmployeeNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameResponse> EmployeeNameAsync() {
            EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.EmployeeNameRequestBody();
            return ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).EmployeeNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressResponse EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.EmployeeAddress(EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequest request) {
            return base.Channel.EmployeeAddress(request);
        }
        
        public string EmployeeAddress() {
            EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequestBody();
            EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressResponse retVal = ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).EmployeeAddress(inValue);
            return retVal.Body.EmployeeAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressResponse> EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.EmployeeAddressAsync(EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequest request) {
            return base.Channel.EmployeeAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressResponse> EmployeeAddressAsync() {
            EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.EmployeeAddressRequestBody();
            return ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).EmployeeAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberResponse EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.EmployeePhoneNumber(EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequest request) {
            return base.Channel.EmployeePhoneNumber(request);
        }
        
        public string EmployeePhoneNumber() {
            EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequestBody();
            EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberResponse retVal = ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).EmployeePhoneNumber(inValue);
            return retVal.Body.EmployeePhoneNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberResponse> EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.EmployeePhoneNumberAsync(EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequest request) {
            return base.Channel.EmployeePhoneNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberResponse> EmployeePhoneNumberAsync() {
            EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.EmployeePhoneNumberRequestBody();
            return ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).EmployeePhoneNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeePrototypeApplication.SOAPServiceReference.LoadDataResponse EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.LoadData(EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequest request) {
            return base.Channel.LoadData(request);
        }
        
        public EmployeePrototypeApplication.SOAPServiceReference.ArrayOfString LoadData(string userid) {
            EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequestBody();
            inValue.Body.userid = userid;
            EmployeePrototypeApplication.SOAPServiceReference.LoadDataResponse retVal = ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).LoadData(inValue);
            return retVal.Body.LoadDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.LoadDataResponse> EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.LoadDataAsync(EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequest request) {
            return base.Channel.LoadDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.LoadDataResponse> LoadDataAsync(string userid) {
            EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.LoadDataRequestBody();
            inValue.Body.userid = userid;
            return ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).LoadDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestResponse EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.SubmitRequest(EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequest request) {
            return base.Channel.SubmitRequest(request);
        }
        
        public void SubmitRequest(string userid, System.DateTime StartDate, System.DateTime EndDate) {
            EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestResponse retVal = ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).SubmitRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestResponse> EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap.SubmitRequestAsync(EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequest request) {
            return base.Channel.SubmitRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestResponse> SubmitRequestAsync(string userid, System.DateTime StartDate, System.DateTime EndDate) {
            EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequest inValue = new EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequest();
            inValue.Body = new EmployeePrototypeApplication.SOAPServiceReference.SubmitRequestRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((EmployeePrototypeApplication.SOAPServiceReference.SOAPWebServiceSoap)(this)).SubmitRequestAsync(inValue);
        }
        
        public bool CalendarCompareDateValidation(System.DateTime StartDate, System.DateTime EndDate) {
            return base.Channel.CalendarCompareDateValidation(StartDate, EndDate);
        }
        
        public System.Threading.Tasks.Task<bool> CalendarCompareDateValidationAsync(System.DateTime StartDate, System.DateTime EndDate) {
            return base.Channel.CalendarCompareDateValidationAsync(StartDate, EndDate);
        }
    }
}
